#!/usr/bin/env node
/**
 * make-icons.mjs — regenerate the inline icon path data from Font Awesome.
 *
 * The site uses ~30 of Font Awesome's ~2000 icons. Loading them as a webfont
 * cost 277 kB (fa-solid-900.woff2 + fa-brands-400.woff2) plus 72 kB of CSS
 * that maps every class name in the set. Inlining just the paths costs a few
 * kB of JS instead, and drops two render-blocking font fetches.
 *
 * Two files are emitted:
 *   src/data/icons.js    — icons the page itself renders (in the main bundle)
 *   src/data/cvIcons.js  — icons only the CV exporters draw (in lazy chunks)
 *
 * Run after adding an icon to ICONS below:
 *   npm run icons
 *
 * @fortawesome/fontawesome-free is a devDependency only — nothing in the
 * shipped bundle imports it.
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..')
const FA = join(ROOT, 'node_modules', '@fortawesome', 'fontawesome-free', 'svgs')

// Keyed by the name used in JSX (<Icon name="..." />) or by the exporters.
// Several Font Awesome 5 names the site was written against are aliases in
// 6.x, so the file they actually live in is spelled out where it differs.
const SETS = {
  'src/data/icons.js': {
    exportName: 'ICON_PATHS',
    solid: {
      bars: 'bars',
      'chess-knight': 'chess-knight',
      'chevron-down': 'chevron-down',
      crosshairs: 'crosshairs',
      download: 'download',
      envelope: 'envelope',
      eye: 'eye',
      'feather-pointed': 'feather-pointed',
      'file-csv': 'file-csv',
      'file-excel': 'file-excel',
      'file-lines': 'file-lines',
      'file-pdf': 'file-pdf',
      'file-word': 'file-word',
      guitar: 'guitar',
      heart: 'heart',
      infinity: 'infinity',
      meteor: 'meteor',
      microchip: 'microchip',
      mitten: 'mitten',
      'shield-alt': 'shield-halved',
      spinner: 'spinner',
      times: 'xmark',
      'yin-yang': 'yin-yang',
    },
    brands: {
      github: 'github',
      'js-square': 'square-js',
      linkedin: 'linkedin',
      linux: 'linux',
      markdown: 'markdown',
      python: 'python',
      rust: 'rust',
      telegram: 'telegram',
    },
  },
  'src/data/cvIcons.js': {
    exportName: 'CV_ICON_PATHS',
    solid: {
      award: 'award',
      briefcase: 'briefcase',
      'diagram-project': 'diagram-project',
      envelope: 'envelope',
      globe: 'globe',
      'graduation-cap': 'graduation-cap',
      heart: 'heart',
      'layer-group': 'layer-group',
      'location-dot': 'location-dot',
      terminal: 'terminal',
    },
    brands: {
      github: 'github',
      linkedin: 'linkedin',
      telegram: 'telegram',
    },
  },
}

function read(style, file) {
  const svg = readFileSync(join(FA, style, `${file}.svg`), 'utf8')
  const viewBox = svg.match(/viewBox="([^"]+)"/)?.[1]
  const path = svg.match(/ d="([^"]+)"/)?.[1]
  if (!viewBox || !path) throw new Error(`${style}/${file}.svg: no viewBox or path`)
  const [, , w, h] = viewBox.split(/\s+/).map(Number)
  return { w, h, path }
}

for (const [rel, set] of Object.entries(SETS)) {
  const entries = []
  for (const style of ['solid', 'brands']) {
    for (const [name, file] of Object.entries(set[style] ?? {})) {
      const { w, h, path } = read(style, file)
      entries.push(`  '${name}': [${w}, ${h}, '${path}'],`)
    }
  }
  const source = `// Generated by scripts/make-icons.mjs — do not edit by hand.
// Each entry is [viewBoxWidth, viewBoxHeight, pathData] from Font Awesome Free
// (CC BY 4.0 — https://fontawesome.com/license/free).
export const ${set.exportName} = {
${entries.sort().join('\n')}
}
`
  const out = join(ROOT, rel)
  writeFileSync(out, source)
  console.log(`wrote ${rel} — ${entries.length} icons, ${(source.length / 1024).toFixed(1)} kB`)
}
